### ISSUE TITLE
failing installation displayed as completed

### ISSUE THREAD

**Issue by mikaoelitiana** [tsirysndr/envhub#49]
I have installed `envhub` using the `bash` and while the installation was unsuccessful due the `mv: rename /tmp/envhub to /usr/local/bin: Permission denied`, the success screen is displayed 

<img width="651" alt="image" src="https://github.com/tsirysndr/envhub/assets/674667/b7a8a17f-5fe7-4fc8-bf26-d59fdd2644f7">

**Comment by tsirysndr** [comment]
Thank you for bringing this issue to my attention, and I appreciate your patience.

I can confirm that the reported issue has been addressed with commit [3ed6f1b](https://github.com/tsirysndr/envhub/commit/3ed6f1b34ade2d0e937b31565554eaad2a92007e). This commit adjusts permissions during the installation process, which resolves the Permission denied error you encountered. 

If you encounter any further issues or have additional feedback, please don't hesitate to let me know
