### ISSUE TITLE
How to use specific version of Homebrew package

### ISSUE THREAD

**Issue by mikaoelitiana** [tsirysndr/envhub#51]
### Discussed in https://github.com/tsirysndr/envhub/discussions/50

<div type='discussions-op-text'>

<sup>Originally posted by **mikaoelitiana** April  2, 2024</sup>
I want to install `neovim` with `HEAD`, how do I set the `@HEAD` version for that in `envhub.hcl` ?</div>

**Comment by tsirysndr** [comment]
it's not supported yet, we still need to find the best way to pass options to homebrew from the `envhub.hcl` file.

**Comment by mikaoelitiana** [comment]
@tsirysndr using the following seems to work

```
homebrew {
  packages = [
    "neovim --HEAD"
  ]
}
```

https://github.com/mikaoelitiana/envhub/blob/f784149b13663ee47e2ae549ca6347acbd06a80e/crates/pkgs/src/homebrew.rs#L86-L91

**Comment by tsirysndr** [comment]
Looks good to me 🙏
I think it will also allow the installation of cask packages #52 
 
```
homebrew {
  packages = [
    "--cask dbeaver-community"
  ]
}
```

**Comment by mikaoelitiana** [comment]
Yes that's right, thanks!
